server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ms-pedidos

  sql:
    init:
      mode: always

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:ep-delicate-night-at23b02k-pooler.c-9.us-east-1.aws.neon.tech}:${DB_PORT:5432}/${DB_NAME:neondb}?sslMode=${DB_SSL_MODE:require}
    username: ${DB_USER:neondb_owner}
    password: ${DB_PASSWORD:npg_OtmMsz98YZEp}

servicios:
  productos-url: ${PRODUCTOS_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
